spring:
  profiles:
    active: standalone
---
spring:
  config:
    activate:
      on-profile: standalone
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

---
spring:
  config:
    activate:
      on-profile: sentinel
  redis:
    password: redis
    sentinel:
      master: mymaster
      nodes:
        - 192.168.11.163:26379
        - 192.168.11.164:26379
        - 192.168.11.165:26379
